spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://walab.handong.edu/p233_22100220?serverTimezone=UTC&characterEncoding=UTF-8
    username: p233_22100220
    password: Fa9Oib
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
